<?php
/**
* This is the language constants file.
* It is generated by {@link lang_conv.php}.
**/

define (STR_MAIN_TITLE, 1);
define (STR_INTRO_PARAGRAPH, 2);
define (STR_HOME, 3);
define (STR_ALL_PACKAGES, 4);
define (STR_VERSION, 5);
define (STR_POWERED_BY, 6);
define (STR_DATE_GENERATED, 7);
define (STR_CLASSES, 8);
define (STR_INTERFACES, 9);
define (STR_FUNCTIONS, 10);
define (STR_FILES, 11);
define (STR_CONSTANTS, 12);
define (STR_SOURCE_CODE, 13);
define (STR_FROM_CLASS, 14);
define (STR_FROM_INTERFACE, 15);
define (STR_AVAIL_SINCE, 16);
define (STR_FILE, 17);
define (STR_ERROR_TITLE, 18);
define (STR_NAME, 19);
define (STR_VALUE, 20);
define (STR_DESCRIPTION, 21);
define (STR_SEARCH_TITLE, 22);
define (STR_SEARCH_GO_BTN, 23);
define (STR_SEARCH_TERM, 24);
define (STR_ADV_SEARCH_TITLE, 25);
define (STR_WHAT_SEARCH, 26);
define (STR_YOU_SEARCHED_FOR, 27);
define (STR_YOU_SEARCHED_FOR_CASE, 28);
define (STR_CLASSES_RESULT, 29);
define (STR_FUNCTIONS_RESULT, 30);
define (STR_CONSTANTS_RESULT, 31);
define (STR_SOURCE_CODE_RESULT, 32);
define (STR_SHOW_HIDE_ALL, 33);
define (STR_SEARCH_OPTIONS, 34);
define (STR_CASE_SENSITIVE, 35);
define (STR_NUM_SOURCE_RESULTS, 36);
define (STR_MORE_INFO, 37);
define (STR_PROJECT_DOCS, 38);
define (STR_ADDITIONAL_DOCS, 39);
define (STR_AUTHOR_LIST_TITLE, 40);
define (STR_AUTHOR_LIST_INTRO, 41);
define (STR_AUTHOR_LIST_NONE, 42);
define (STR_AUTHOR_LIST_DESC, 43);
define (STR_AUTHOR_PAGE_TITLE, 44);
define (STR_AUTHOR_TITLE, 45);
define (STR_TAG_LIST_TITLE, 46);
define (STR_TAG_LIST_INTRO, 47);
define (STR_TAG_LIST_NONE, 48);
define (STR_TAG_LIST_DESC, 49);
define (STR_TAG_PAGE_TITLE, 50);
define (STR_TAG_TITLE, 51);
define (STR_CLASS_TREE_TITLE, 52);
define (STR_CLASS_TREE_DESC, 53);
define (STR_INVALID_DOCUMENT, 54);
define (STR_ENUM_BROWSER_TITLE, 55);
define (STR_ENUM_PAGE_TITLE, 56);
define (STR_ENUM_VIRTUAL, 57);
define (STR_ENUM_INVALID, 58);
?>
