<?php
/**
* This is the language constants file.
* It is generated by {@link lang_conv.php}.
**/

define (STR_MAIN_TITLE, 1);
define (STR_INTRO_PARAGRAPH, 2);
define (STR_HOME, 3);
define (STR_ALL_PACKAGES, 4);
define (STR_MORE_INFO, 5);
define (STR_VERSION, 6);
define (STR_POWERED_BY, 7);
define (STR_DATE_GENERATED, 8);
define (STR_CLASSES, 9);
define (STR_INTERFACES, 10);
define (STR_FUNCTIONS, 11);
define (STR_FILES, 12);
define (STR_CONSTANTS, 13);
define (STR_SOURCE_CODE, 14);
define (STR_SEARCH_TITLE, 15);
define (STR_SEARCH_GO_BTN, 16);
define (STR_SEARCH_TERM, 17);
define (STR_ADV_SEARCH_TITLE, 18);
define (STR_WHAT_SEARCH, 19);
define (STR_YOU_SEARCHED_FOR, 20);
define (STR_CLASSES_RESULT, 21);
define (STR_FUNCTIONS_RESULT, 22);
define (STR_CONSTANTS_RESULT, 23);
define (STR_SOURCE_CODE_RESULT, 24);
define (STR_SHOW_HIDE_ALL, 25);
?>
